In [2]:
from __future__ import division
from dataset import Dataset
import numpy as np
import os

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import pickle

In [6]:
ground_truth = pickle.load(open('data/test2/201705262030_label.pkl', 'rb'))
predicted = pickle.load(open('data/test2/prediction.pkl', 'rb'))

In [10]:
from sklearn.metrics import accuracy_score

In [17]:
prediction = np.array([])
for i in predicted:
    prediction = np.concatenate((prediction, i))

In [19]:
accuracy_score(ground_truth, prediction[:ground_truth.shape[0]])

0.8762391557201242

In [3]:
data_dir = os.getcwd() + '/data'
n_context = 1
segment_length = 50
batch_size = 256
dataset = Dataset(data_path = data_dir,
                   n_context = n_context,
                   stride = 1,
                   segment_length = segment_length,
                   batch_size = batch_size,
                   split_train_dev = True,
                   shuffle = True)

(5625, 50, 369)
(5625, 50, 3)
(5625,)


In [151]:
a,b,c = dataset.next_batch()
print(dataset.idx)
dataset.train_inputs[0]

256


array([[ 1.2503271 ,  1.038073  ,  0.78141814, ..., -0.00569564,
         0.07546563,  0.06461786],
       [ 0.7769158 ,  0.7861219 ,  1.122538  , ..., -0.65259284,
         0.2611794 ,  1.5335294 ],
       [ 1.2555012 ,  0.9646084 ,  1.0913619 , ..., -0.770786  ,
         0.42611995,  1.8012671 ],
       ...,
       [ 1.4509265 ,  1.2247381 ,  0.86530536, ..., -0.265769  ,
         0.3505192 , -0.5341072 ],
       [ 1.1645927 ,  0.94578683,  0.8416453 , ..., -0.14272945,
        -0.27286515, -0.71066785],
       [ 1.3325456 ,  1.2948881 ,  1.0576451 , ...,  0.0621113 ,
        -0.8503299 , -0.77134293]], dtype=float32)

In [161]:
a[0]

array([[ 1.2503271 ,  1.038073  ,  0.78141814, ..., -0.00569564,
         0.07546563,  0.06461786],
       [ 0.7769158 ,  0.7861219 ,  1.122538  , ..., -0.65259284,
         0.2611794 ,  1.5335294 ],
       [ 1.2555012 ,  0.9646084 ,  1.0913619 , ..., -0.770786  ,
         0.42611995,  1.8012671 ],
       ...,
       [ 1.4509265 ,  1.2247381 ,  0.86530536, ..., -0.265769  ,
         0.3505192 , -0.5341072 ],
       [ 1.1645927 ,  0.94578683,  0.8416453 , ..., -0.14272945,
        -0.27286515, -0.71066785],
       [ 1.3325456 ,  1.2948881 ,  1.0576451 , ...,  0.0621113 ,
        -0.8503299 , -0.77134293]], dtype=float32)

In [162]:
np.transpose(a, [1,0,2])

array([[[ 1.2503271e+00,  1.0380729e+00,  7.8141814e-01, ...,
         -5.6956429e-03,  7.5465627e-02,  6.4617857e-02],
        [-1.3789693e+00, -1.4117986e+00, -1.7857589e+00, ...,
          6.7677981e-01,  6.0732734e-01,  1.5648661e-02],
        [ 9.6813649e-01,  1.2952622e+00,  9.6023911e-01, ...,
          2.3962064e-01,  6.7151201e-01,  1.1916864e-01],
        ...,
        [-8.4356630e-01, -9.7969288e-01, -1.1198052e+00, ...,
         -2.1386248e-01,  1.4807394e-02,  1.1911838e-02],
        [-1.1953987e+00, -1.3768647e+00, -1.0098335e+00, ...,
         -1.3815697e+00,  1.5607633e-01,  1.6276488e-03],
        [ 1.7409627e-01,  1.1029392e+00,  9.7279829e-01, ...,
          5.0571311e-01,  2.5388449e-01, -8.1723315e-01]],

       [[ 7.7691579e-01,  7.8612190e-01,  1.1225380e+00, ...,
         -6.5259284e-01,  2.6117939e-01,  1.5335294e+00],
        [-1.5787379e+00, -1.5937500e+00, -1.6721219e+00, ...,
          6.7535967e-01,  6.8968642e-01,  5.4886565e-02],
        [ 9.6593982e-01, 

In [159]:
print(np.shape(a))
np.transpose(a, [1,0,2]).reshape((-1, 369))

(256, 50, 369)


array([[ 1.2503271 ,  1.038073  ,  0.78141814, ..., -0.00569564,
         0.07546563,  0.06461786],
       [-1.3789693 , -1.4117986 , -1.7857589 , ...,  0.6767798 ,
         0.60732734,  0.01564866],
       [ 0.9681365 ,  1.2952622 ,  0.9602391 , ...,  0.23962064,
         0.671512  ,  0.11916864],
       ...,
       [-0.9627457 , -0.828611  , -0.78145564, ...,  0.3911142 ,
        -0.08375822,  0.06614749],
       [-1.0053899 , -1.1288817 , -1.1158162 , ..., -0.24844915,
         0.03509361, -0.04550619],
       [ 0.5194993 ,  0.49049148,  1.1555343 , ...,  0.31217453,
        -0.38787758,  0.48028606]], dtype=float32)

(256, 50, 369)